backend: drupal
extensions:
  - layout_builder
frameworks:
  component: sdc
  css: daisyui
dist: packages/integrations/test-integration-drupal/designbook
tmp: packages/integrations/test-integration-drupal/designbook/tmp
drupal:
  theme: packages/integrations/test-integration-drupal
