backend: drupal
frameworks:
  component: sdc
  css: tailwind
extensions:
  - id: canvas
    url: https://www.drupal.org/project/experience_builder
dist: packages/integrations/test-integration-drupal/designbook
tmp: packages/integrations/test-integration-drupal/designbook/tmp
css:
  app: packages/integrations/test-integration-drupal/css/app.src.css
drupal:
  theme: packages/integrations/test-integration-drupal
cmd: node packages/storybook-addon-designbook/dist/cli.js
storybook_url: "http://localhost:6009"
storybook_root: packages/integrations/test-integration-drupal/
