# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - "System: You are a helpful customer service assistant for a widget store. You are empathetic and concise.\n\nUser: Fulfill this user helpdesk ticket: {{inquiry}}"
  

providers:
  - id: opencode:google/antigravity-gemini-3-pro
    config:
      temperature: 0.7


tests:
  - vars:
      inquiry: "Who are you?"
    assert:
      - type: icontains
        value: "OpenCode"
  - vars:
      inquiry: "Write a hello world in Python"
    assert:
      - type: icontains
        value: "print"
