workspace: .

backend: drupal
frameworks:
  component: sdc
  css: tailwind
extensions:
  - id: canvas
    url: https://www.drupal.org/project/canvas
  - id: stitch
designbook:
  cmd: npx storybook dev
  home: .
  url: "http://localhost:6009"
dirs:
  components: components
  css: css/tokens
css:
  app: css/app.src.css
component:
  namespace: 'test_integration_drupal'
  src: components
