title: Define Product Vision
workflow: vision
workflow_id: 7db2
status: incomplete
engine: direct
stages:
  create-vision:
    steps:
      - create-vision
stage_loaded:
  create-vision:
    task_file: .claude/skills/designbook/vision/tasks/create-vision.md
    rules: []
    blueprints: []
    config_rules: []
    config_instructions: []
    schema:
      definitions:
        Vision:
          type: object
          required:
            - product_name
            - description
          properties:
            product_name:
              type: string
              title: Product Name
            description:
              type: string
              title: Description
            problems:
              type: array
              title: Problems & Solutions
              default: []
              items:
                type: object
                properties:
                  title:
                    type: string
                  solution:
                    type: string
            features:
              type: array
              title: Key Features
              default: []
              items:
                type: string
            design_reference:
              type: object
              title: Design Reference
              default: null
              properties:
                type:
                  type: string
                url:
                  type: string
                label:
                  type: string
            references:
              type: array
              title: References
              default: []
              items:
                type: object
                properties:
                  type:
                    type: string
                  url:
                    type: string
                  label:
                    type: string
      params:
        vision:
          type: object
          path: /home/cw/projects/designbook/designbook/vision.yml
          exists: false
          content: null
      result:
        vision:
          path: /home/cw/projects/designbook/designbook/vision.yml
          exists: false
          content: null
          $ref: '#/definitions/Vision'
current_stage: create-vision
started_at: '2026-04-16T18:48:59'
workspace_root: /home/cw/projects/designbook
schemas:
  Vision: &ref_0
    type: object
    required:
      - product_name
      - description
    properties:
      product_name:
        type: string
        title: Product Name
      description:
        type: string
        title: Description
      problems:
        type: array
        title: Problems & Solutions
        default: []
        items:
          type: object
          properties:
            title:
              type: string
            solution:
              type: string
      features:
        type: array
        title: Key Features
        default: []
        items:
          type: string
      design_reference:
        type: object
        title: Design Reference
        default: null
        properties:
          type:
            type: string
          url:
            type: string
          label:
            type: string
      references:
        type: array
        title: References
        default: []
        items:
          type: object
          properties:
            type:
              type: string
            url:
              type: string
            label:
              type: string
env_map:
  DESIGNBOOK_TECHNOLOGY: html
  DESIGNBOOK_WORKSPACE: /home/cw/projects/designbook
  DESIGNBOOK_HOME: /home/cw/projects/designbook
  DESIGNBOOK_DATA: /home/cw/projects/designbook/designbook
  DESIGNBOOK_EXTENSIONS: ''
  DESIGNBOOK_EXTENSION_SKILLS: ''
tasks:
  - id: create-vision
    title: 'Define Product Vision: create-vision'
    type: data
    step: create-vision
    stage: create-vision
    status: in-progress
    started_at: '2026-04-16T18:48:59'
    task_file: .claude/skills/designbook/vision/tasks/create-vision.md
    files: []
    result:
      vision:
        path: /home/cw/projects/designbook/designbook/vision.yml
        schema: *ref_0
completed_at: '2026-04-16T18:49:09'
summary: 'Define Product Vision: create-vision (data)'
