#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    dbfix-1799556576-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^dbfix-1799556576\.ddev\.site$`)
      
      service: "dbfix-1799556576-web-80"
      tls: false
      # middlewares:
      #   - "dbfix-1799556576-redirectHttps"
    dbfix-1799556576-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^dbfix-1799556576\.ddev\.site$`)
      
      service: "dbfix-1799556576-web-8025"
      tls: false
      # middlewares:
      #   - "dbfix-1799556576-redirectHttps"
    dbfix-1799556576-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^dbfix-1799556576\.ddev\.site$`)
      
      service: "dbfix-1799556576-xhgui-80"
      tls: false
      # middlewares:
      #   - "dbfix-1799556576-redirectHttps"
    
    
    
    dbfix-1799556576-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^dbfix-1799556576\.ddev\.site$`)
      
      service: "dbfix-1799556576-web-80"
      
      tls: true
      
    dbfix-1799556576-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^dbfix-1799556576\.ddev\.site$`)
      
      service: "dbfix-1799556576-web-8025"
      
      tls: true
      
    
    dbfix-1799556576-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^dbfix-1799556576\.ddev\.site$`)
      
      service: "dbfix-1799556576-xhgui-80"
      
      tls: true
      
    

  middlewares:
    dbfix-1799556576-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    dbfix-1799556576-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-dbfix-1799556576-web:80
        
    dbfix-1799556576-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-dbfix-1799556576-web:8025
        
    
    
    dbfix-1799556576-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-dbfix-1799556576-xhgui:80
        
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/dbfix-1799556576.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/dbfix-1799556576.key