/**
 * Vitest plugin for SDC (Single Directory Components) story testing.
 *
 * Wraps @storybook/addon-vitest with SDC-specific workarounds:
 * - Deduplicates `import COMPONENT` declarations from multi-twig components
 * - Fixes node:stream/promises polyfill conflict from storybook-addon-sdc
 */

import type { Plugin } from 'vite';

/**
 * Fix duplicate COMPONENT imports generated by storybook-addon-sdc.
 *
 * When a component has variant includes (e.g. card--horizontal.twig),
 * the SDC addon generates multiple `import COMPONENT from '...'` declarations.
 * This plugin keeps only the first and converts the rest to side-effect imports.
 *
 * Must be registered BEFORE storybookTest() in the plugins array so it runs
 * before vite-plugin-storybook-test's babel transform.
 */
export function sdcDedupPlugin(): Plugin {
  return {
    name: 'sdc-dedup-vitest',
    transform(code: string, id: string) {
      const cleanId = id.split('?')[0]!;
      if (!cleanId.endsWith('.component.yml')) return;
      if (!code.includes('import COMPONENT')) return;
      let found = false;
      return code.replace(
        /import COMPONENT from '([^']+)';/g,
        (match: string, importPath: string) => {
          if (!found) {
            found = true;
            return match;
          }
          return `import '${importPath}';`;
        },
      );
    },
  };
}

/**
 * Returns all SDC-specific Vite plugins needed for vitest story testing.
 *
 * Usage in vitest.config.ts:
 * ```ts
 * import { sdcVitestPlugins } from 'storybook-addon-designbook/vitest-plugin-sdc';
 * import { storybookTest } from '@storybook/addon-vitest/vitest-plugin';
 *
 * export default defineConfig({
 *   test: {
 *     projects: [{
 *       plugins: [
 *         ...sdcVitestPlugins(),
 *         storybookTest({ configDir: '.storybook' }),
 *       ],
 *     }],
 *   },
 * });
 * ```
 */
export function sdcVitestPlugins(): Plugin[] {
  return [sdcDedupPlugin()];
}
