title: Define Data Model
workflow: data-model
workflow_id: '6861'
status: running
engine: direct
stages:
  intake:
    steps:
      - data-model:intake
  execute:
    steps:
      - create-data-model
stage_loaded:
  data-model:intake:
    task_file: >-
      /home/cw/projects/designbook/.claude/skills/designbook/data-model/tasks/intake--data-model.md
    rules: &ref_0
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/rules/media-image-styles.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/rules/drupal-views.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook/data-model/rules/sample-template-mapping.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook/data-model/rules/image-style-config.md
    blueprints: &ref_1
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/blueprints/view.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/blueprints/taxonomy_term.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/blueprints/node.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/blueprints/media.md
    config_rules: []
    config_instructions: []
  create-data-model:
    task_file: >-
      /home/cw/projects/designbook/.claude/skills/designbook/data-model/tasks/create-data-model.md
    rules:
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/rules/media-image-styles.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook-drupal/data-model/rules/drupal-views.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook/data-model/rules/sample-template-mapping.md
      - >-
        /home/cw/projects/designbook/.claude/skills/designbook/data-model/rules/image-style-config.md
    blueprints: []
    config_rules: []
    config_instructions: []
current_stage: intake
started_at: '2026-04-11T09:22:57'
tasks:
  - id: intake
    title: 'Intake: Define Data Model'
    type: data
    step: data-model:intake
    stage: intake
    status: in-progress
    started_at: '2026-04-11T09:22:57'
    task_file: >-
      /home/cw/projects/designbook/.claude/skills/designbook/data-model/tasks/intake--data-model.md
    rules: *ref_0
    blueprints: *ref_1
    files: []
